version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexora
      POSTGRES_PASSWORD: nexora_secret
      POSTGRES_DB: nexora
    ports:
      - '5432:5432'
    volumes:
      - nexora_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nexora -d nexora']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexora-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - nexora_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  nexora_pg_data:
  nexora_redis_data:
